name: build binary

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r23d
    - name: make
      run: make
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: libs/armeabi-v7a/dirtycow
